# Default values for edge-sip2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: folioorg/edge-sip2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

resources:
  limits:
    # cpu: 100m
    memory: 384Mi
  requests:
    # cpu: 50m
    memory: 256Mi

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 4
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Should be set to NodePort if ingress for AWS ALB enabled
service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      containerPort: 6443
      targetPort: http
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

args:
  - -conf
  - /etc/edge/sip2.conf

## @param javaOpts Custom JVM parameters
##
javaOpts:
  - "-Dokapi_url=http://$(OKAPI_HOST):$(OKAPI_PORT)"

extraJavaOpts:
  - "-XX:MaxRAMPercentage=75.0"
  # - "-Dlog_level=DEBUG"

extraEnvVars: []
  # - name: FOO
  #   value: bar

extraEnvVarsSecrets: []
  # = foo-secret
  # - bar-secret

jmx:
  enabled: false
  port: 1099

eureka:
  enabled: false
  sidecarContainer: {}

heapDumpEnabled: false

volumeClaims:
  extendedtmp:
    enabled: false
    name: &extendedtmp_name '{{ printf "%s-%s" (include "folio-common.fullname" $) "extendedtmp" }}'
    storageClassName: gp2
    size: 20Gi
    accessModes: ReadWriteOnce
    existingClaim:

extraVolumeMounts:
  heapdump:
    enabled: false
    name: heapdump
    mountPath: /tmp/dump
  extendedtmp:
    enabled: false
    name: extendedtmp
    mountPath: /tmp

extraVolumes:
  heapdump:
    enabled: false
    name: heapdump
    emptyDir: {}
  extendedtmp:
    enabled: false
    name: extendedtmp
    persistentVolumeClaim:
      claimName: *extendedtmp_name

initContainer:
  enabled: false
  image:
    repository: busybox
    tag: latest
    pullPolicy: Always
    command: '["sh", "-c", "chown -R 1000:1000 /tmp"]'
  args:
  extraVolumeMounts:
    extendedtmp:
      enabled: false
      name: extendedtmp
      mountPath: /tmp

integrations:
  okapi:
    enabled: true
    host: okapi
    port: 9130
    url: http://okapi:9130
    existingSecret: ""

configMaps:
  ephemeral:
    enabled: true
    fileName: ephemeral.properties
    mountPath: /etc/edge
    existingConfig: ""
  sip2config:
    enabled: true
    fileName: sip2.conf
    mountPath: /etc/edge
    existingConfig: ""
  sip2tenants:
    enabled: true
    fileName: sip2-tenants.conf
    mountPath: /etc/edge
    existingConfig: ""

okapiUrl: http://okapi:9130

sip2TenantsConfig: |-
  {
    "scTenants": [
      {
        "scSubnet": "0.0.0.0/0",
        "tenant": "diku",
        "errorDetectionEnabled": false,
        "messageDelimiter": "\r",
        "charset": "ISO-8859-1"
      }
    ]
  }

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

startupProbe: {}
readinessProbe: {}
livenessProbe: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}
