extends: default
rules:
  line-length:
    max: 120
  document-start: disable
  truthy:
    allowed-values: [ 'true', 'false', 'on', 'off' ]
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
