{{- define "common.configmap" -}}
{{- if .Values.config }}
{{- range $map := .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $map.name }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
data:
  {{ $map.subPath }}: |-
{{ tpl ($.Files.Get (printf "configmaps/%s" $map.name)) $ | indent 4 }}
{{- end }}
{{- end }}
{{- end -}}
