{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.name" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ .Values.service.portName | default "http" }}
    {{- if .Values.jmxMetrics }}
    - port: {{ .Values.jmxMetrics.containerPort | default 9991 }}
      targetPort: {{ .Values.jmxMetrics.containerPort | default 9991 }}
      protocol: TCP
      name: {{ .Values.jmxMetrics.portName | default "jmx" }}
    {{- end }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
{{- end -}}
