# Default values for edge-erm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: folioorg/edge-erm
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

resources:
  limits:
    # cpu: 100m
    memory: 340Mi
  requests:
    # cpu: 50m
    memory: 295Mi

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 4
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Should be set to NodePort if ingress for AWS ALB enabled
service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      containerPort: 8080
      targetPort: http
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /erm*
          pathType: ImplementationSpecific

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

args: []

## @param javaOpts Custom JVM parameters
##
javaOpts:
  - "-Dfolio.client.okapiUrl=http://$(OKAPI_HOST):$(OKAPI_PORT)"

extraJavaOpts:
  - "-XX:MaxRAMPercentage=85.0"
  # - "-Dlog_level=DEBUG"

extraEnvVars: []
  # - name: FOO
  #   value: bar

extraEnvVarsSecrets: []
  # = foo-secret
  # - bar-secret

jmx:
  enabled: false
  port: 1099

eureka:
  enabled: false
  envVars: []
  # - name: FOO
  #   value: ba
  extraEnvVars: []
  # - name: FOO
  #   value: ba

heapDumpEnabled: false

volumeClaims:
  extendedtmp:
    enabled: false
    name: &extendedtmp_name '{{ printf "%s-%s" (include "folio-common.fullname" $) "extendedtmp" }}'
    storageClassName: gp2
    size: 20Gi
    accessModes: ReadWriteOnce
    existingClaim:

extraVolumeMounts:
  heapdump:
    enabled: false
    name: heapdump
    mountPath: /tmp/dump
  extendedtmp:
    enabled: false
    name: extendedtmp
    mountPath: /tmp

extraVolumes:
  heapdump:
    enabled: false
    name: heapdump
    emptyDir: {}
  extendedtmp:
    enabled: false
    name: extendedtmp
    persistentVolumeClaim:
      claimName: *extendedtmp_name

initContainer:
  enabled: false
  image:
    repository: busybox
    registry: 732722833398.dkr.ecr.us-west-2.amazonaws.com
    tag: latest
    pullPolicy: IfNotPresent
    command: '["sh", "-c", "chown -R 1000:1000 /tmp"]'
  args:
  extraVolumeMounts:
    extendedtmp:
      enabled: false
      name: extendedtmp
      mountPath: /tmp

integrations:
  okapi:
    enabled: false
    host: okapi
    port: 9130
    url: http://okapi:9130
    existingSecret: ""

  eureka-edge:
    enabled: '{{ .Values.eureka.enabled }}'
    existingSecret: "eureka-edge"

configMaps:
  ephemeral:
    enabled: true
    fileName: ephemeral.properties
    mountPath: /etc/edge
    existingConfig: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

startupProbe: {}
readinessProbe: {}
livenessProbe: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}
