{{- define "common.persistent-disk" -}}
{{- if .Values.volumeMounts.pvc }}
{{- range $pvc := .Values.volumeMounts.pvc }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvc.name }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
  {{- if $pvc.annotations }}
  annotations:
    {{- $pvc.annotaions | toYaml | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- $pvc.accessModes | toYaml | nindent 4 }}
{{- if $pvc.storageClass }}
{{- if (eq "-" $pvc.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ $pvc.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: {{ $pvc.size }}
{{- end }}
{{- end }}
{{- end -}}
