---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hazelcastService.name }}
  labels: {{- include "folio-common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: hazelcast
      protocol: TCP
      port: {{ .Values.hazelcastService.port }}
      targetPort: {{ .Values.hazelcastService.port }}
  selector:
    {{- include "folio-common.selectorLabels" . | nindent 4 }}
